[project]
name = "agria-server"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

dependencies = [
    "numpy<2",
    "pandas",
    "gunicorn",
    "flask",
    "flask-cors",
    "python-dotenv",
    "google-genai",
    "structlog",
    "minio",
    "requests",
    "geopandas",
    "shapely",
    "pyproj",
    "rasterio",
    "fiona",
    "torch~=2.4.0",
    "torchvision",
    "matplotlib",
    "pillow",
    "opencv-python<4.12",
    "scikit-image",
    "rioxarray",
    "sentinelhub",
    "safetensors",
    "protobuf",
    "langchain-openai>=1.3.4",
    "ruff>=0.15.20",
    "pytest>=9.1.1",
    "langchain-core>=1.4.9",
    "sen2sr-tools",
    "sigpac-tools",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "flake8",
    "autopep8",
]

[tool.uv.sources]
sen2sr-tools = { git = "https://github.com/KhaosResearch/sen2sr-tools.git", rev = "main" }
sigpac-tools = { git = "https://github.com/KhaosResearch/sigpac-tools.git", rev = "dev" }
